# -*- coding: utf-8 -*-
"""Análise de Dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EL_-fkYGBJdY6_iefw_4CHv2BRATVWNl

# Instruções

- Certifique-se que a configuração está correta (Python 3).
"""

#👾

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from math import sin, cos, sqrt, atan2, radians
df = pd.read_csv("https://www.dropbox.com/s/8tq1bxi8acps36p/latitude-longitude-bairros.csv?dl=1" , sep=";")

def calcula_distancia_km(df, indice_city1, indice_city2):
    lat1, lon1 = df[['latitude','longitude']].loc[indice_city1]
    lat2, lon2 = df[['latitude','longitude']].loc[indice_city2]
    return lat1, lon1, lat2, lon2

def distancia_terra(lat1, lon1, lat2, lon2):
    lat1, lon1, lat2, lon2 = [radians(lat1), radians(lon1), radians(lat2), radians(lon2)]
    dlon, dlat = [lon2 - lon1, lat2 - lat1]
    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    d = 6371.0 * 2 * atan2(sqrt(a), sqrt(1 - a)) # 6371.0 = raio aproximado da terra
    return d

indice_city1 = float(input())
indice_city2 = float(input())
lat1, lon1, lat2, lon2 = calcula_distancia_km(df, indice_city1, indice_city2)
print('%.2f' % distancia_terra(lat1, lon1, lat2, lon2))

#👾

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv("https://www.dropbox.com/s/ng1pa3ch1uq5e4s/fake-classrooms26.csv?dl=1")

def calculaNota(linha):
  m = (linha["Prova 1"] + linha["Prova 2"] + linha["Trabalho"]) / 3
  return m

def c(df, a, b, c, d):
  if (10 >= df['Nota'] >= a):
    return 'A'
  elif a > df['Nota'] >= b:
    return 'B'
  elif b > df['Nota'] >= c:
    return 'C'
  elif c > df['Nota'] >= d:
    return 'D'
  elif d > df['Nota']:
    return 'F'

def formataConceito(df):
  hist = df['Conceito'].value_counts()
  resp = ''
  if 'A'  in hist.keys(): # verifica se tem algum conceito A
    resp += 'A: %d\n' % hist['A']
  if 'B' in hist.keys():
    resp += 'B: %d\n' % hist['B']
  if 'C' in hist.keys():
    resp += 'C: %d\n' % hist['C']
  if 'D' in hist.keys():
    resp += 'D: %d\n' % hist['D']
  if 'F' in hist.keys():
    resp += 'F: %d\n' % hist['F']
  return str(resp)

notaA = float(input())
notaB = float(input())
notaC = float(input())
notaD = float(input())
df['Nota'] = df.apply(calculaNota, axis=1)
df['Conceito'] = df.apply(c, axis=1, args=[notaA, notaB, notaC, notaD])
print(formataConceito(df))

#👾

import pandas as pd
import numpy as np
df = pd.read_csv("https://www.dropbox.com/s/54k7jbnwkb4wgzo/fake-classrooms18.csv?dl=1")
x = input()
r = df[x].values.var()
print('%.2f' % r)

#👾

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv("https://www.dropbox.com/s/6ovye11b21lyrcu/fake-mercado16.csv?dl=1")
x = input()
df1 = df[df.Categoria == x]
df2 = df1[df1.Valor < 3]
a = df2.values.tolist()
print("Item; Valor; Quantidade")

for lista in a:
  print(lista[1], ";", lista[2], ";", lista[3])

#👾

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df1 = pd.read_csv("https://www.dropbox.com/s/6ovye11b21lyrcu/fake-mercado16.csv?dl=1")
df2 = pd.read_csv("https://www.dropbox.com/s/3ct29fo86g3vynx/fake-mercado01.csv?dl=1")
df3 = pd.read_csv("https://www.dropbox.com/s/da1l9hbe8f0sgy8/fake-mercado19.csv?dl=1")
mercado = [df1, df2, df3]

registro = []
for x in range(0,7):
  a = input()
  itens = []
  for z in range(0,3):
    filtro = mercado[z].query("Item == '"+a+"'").values.tolist()
    itens.append(filtro)
  registro.append(itens)

lista = []
for itens in registro:
  valor = []
  for mercado in itens:
    for colunas in mercado:
      valor.append(colunas[2])
  m = min(valor)
  for y in range(0,3):
    if (valor[y] == m):
      n = y + 1            #mercado com menor valor
      lista.append([colunas[0], colunas[1], m, n])

df_novo = pd.DataFrame(lista, columns=['Categoria', 'Item', 'Menor Valor', 'Mercado'])
df_novo.sort_values(by= ['Categoria', 'Item'], inplace=True)
print(df_novo.to_string(index=False))

#👾

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv("https://www.dropbox.com/s/i554mvb8b3ubpcx/fake-mercado20.csv?dl=1")
t = 0
lista = []
for i in range(0,10):
  a = input()
  a = df.query("Item =='"+a+"'").values.tolist()
  lista.append(a)

todos = []
for itens in lista:
  for item in itens:
    if item[3] > 2:
      subtotal =  item[2] * 2
      item[3] = 2
    else:
      subtotal = item[2] * item[3]
    todos.append([item[0], item[1], item[2], item[3], subtotal])

df_novo = pd.DataFrame(todos, columns=['Categoria', 'Item', 'Valor', 'Quantidade', 'Subtotal'])
df_novo.sort_values(by= ['Categoria', 'Item'], inplace=True)
print(df_novo.to_string(index=False))

#👾

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv("https://www.dropbox.com/s/tcbxw0s0edp3ghm/fake-mercado14.csv?dl=1")
x = input()
df1 = df[df.Categoria == x]
df2 = df1[df1.Quantidade == 2]
df2["Gasto"] = (df1["Valor"] * 10)
a = df2.values.tolist()
print("Item; Valor; Quantidade; Gasto")

for lista in a:
  print(lista[1], ";", lista[2], ";", lista[3], ";", '%.2f' % lista[4])

b = df2["Gasto"].sum()
print("Total gasto para repor os estoques: " '%.2f' % b)

#👾

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("https://www.dropbox.com/s/cpo4eyqoztwn3nc/fake-classrooms-correl07.csv?dl=1")
coluna = input()
df2 = pd.DataFrame([df['Nota Final'], df[coluna]]).transpose()
df2_max = df2.max()
normalizado = df2/df2_max
print(str(normalizado.head()))

#👾

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("https://www.dropbox.com/s/i0wm90ln9zarj7k/fake-classrooms-correl11.csv?dl=1")
coluna = input()
tab_XY = df[['Nota Final', coluna]]
(a, b) = np.polyfit(x=tab_XY[coluna], y=tab_XY['Nota Final'], deg=1)
modelo = a*df[coluna]+b
n = modelo.rename('Estimativa')
df2 = pd.DataFrame([df['Nota Final'], n]).transpose()
print(str(df2.head()))

#👾

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv("https://www.dropbox.com/s/i554mvb8b3ubpcx/fake-mercado20.csv?dl=1")
t = 0
lista = []
for i in range(0,10):
  a = input()
  a = df.query("Item =='"+a+"'").values.tolist()
  lista.append(a)

todos = []
for itens in lista:
  for item in itens:
    if item[3] > 2:
      subtotal =  item[2] * 2
      item[3] = 2
    else:
      subtotal = item[2] * item[3]
    todos.append([item[0], item[1], item[2], item[3], subtotal])

df_novo = pd.DataFrame(todos, columns=['Categoria', 'Item', 'Valor', 'Quantidade', 'Subtotal'])
df_novo.sort_values(by= ['Categoria', 'Item'], inplace=True)
print(df_novo.to_string(index=False))

"""# 👾 Algumas das tabelas disponiveis para visualização abaixo:"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from math import sin, cos, sqrt, atan2, radians
df = pd.read_csv("https://www.dropbox.com/s/8tq1bxi8acps36p/latitude-longitude-bairros.csv?dl=1" , sep=";")
df

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv("https://www.dropbox.com/s/i554mvb8b3ubpcx/fake-mercado20.csv?dl=1")
df